name: Build and Deploy unocss Docs

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install -r

      - name: Build project
        run: pnpm build

      - name: Build documentation
        run: |
          cd docs
          pnpm docs:build

      - name: Deploy to Site Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dist
          publish_branch: _site
          force_orphan: true
